# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_tel', models.CharField(max_length=11)),
                ('p_height', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Player')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
