# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Student'),
        ),
    ]
