# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_studentinfo_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='i_unage',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
