# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0007_auto_20180505_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_delete',
            field=models.BooleanField(default=1),
        ),
    ]
