# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_sex',
            field=models.BooleanField(default=0),
        ),
    ]
