# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20180424_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_shuxue',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_yuwen',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
