# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=20)),
                ('g_des', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
    ]
