# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=10)),
                ('stu_sex', models.BooleanField()),
                ('stu_birth', models.DateField()),
                ('stu_height', models.CharField(max_length=5)),
                ('stu_tel', models.CharField(max_length=11)),
                ('stu_email', models.CharField(max_length=20)),
                ('stu_grade', models.CharField(max_length=20)),
                ('stu_interest', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
