# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monks',
            fields=[
                ('monk_id', models.AutoField(primary_key=True, serialize=False)),
                ('monk_name', models.CharField(max_length=10)),
                ('monk_sex', models.BooleanField()),
                ('monk_tel', models.CharField(max_length=11)),
                ('monk_birth', models.DateField()),
                ('monk_delete_date', models.BooleanField(default=0)),
                ('monk_create_time', models.DateField(auto_now_add=True)),
                ('monk_operate_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
