# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20180425_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='g_id',
            new_name='g',
        ),
    ]
